version: '3.8'

services:
    nodejs-backend:
        build: ./nodejs-backend
        depends_on:
            - postgres
        ports: 
            - 5000:5000
        
        
    gameflex-vue:
        build: ./gameflex-vue
        depends_on:
    
            - postgres
        ports: 
            - 3000:3000
    postgres:
      image: postgres:14.1-alpine
      restart: always
      environment:

      #Kendi kullanici adi ve sifrenizi girin.
    
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=65953900
        - POSTGRES_DB=gameflex
      ports:
        - "6543:5432"
      volumes:
        
        - ./database-seed.sql:/docker-entrypoint-initdb.d/database-seed.sql